openapi: 3.0.0
info:
  description: Access and Mobility Policy Control Service API
  version: "1.0.0"
  title: Npcf_AMPolicyControl
externalDocs:
  description: 3GPP TS 29.507 V15.2.0; 5G System; Access and Mobility Policy Control Service.
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.507/'
servers:
  - url: '{apiRoot}/test-microservice/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in subclause subclause 4.4 of 3GPP TS 29.501

paths:
  /validations/parameters/queries/json:
    get:
      operationId: testJsonQueryParam
      parameters:
        - name: ipv4Addr
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Ipv4Addr'
        - name: snssai
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Snssai'
        - name: plmnId
          in: query
          required: false
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlmnId'
      responses:
        '200':
          description: OK

components:
  schemas:
    Ipv4Addr:
      type: string
    Mcc:
      type: string
      pattern: '^\d{3}$'
    Mnc:
      type: string
      pattern: '^\d{2,3}$'
    PlmnId:
      type: object
      properties:
        mcc:
          $ref: '#/components/schemas/Mcc'
        mnc:
          $ref: '#/components/schemas/Mnc'
      required:
        - mcc
        - mnc
    Snssai:
      type: object
      properties:
        sst:
          type: integer
          minimum: 0
          maximum: 255
        sd:
          type: string
          pattern: '^[A-Fa-f0-9]{6}$'
      required:
        - sst
